### ISSUE TITLE
Cannot create  new smart agent project; generator-evan fails!

### ISSUE THREAD

**Issue by fBruzja** [evannetwork/workshop-hem#2]
While going through the steps of creating the smart agent project called by `yo evan`, after i claim my own preferred subdomain the process fails and gives the error below: 

Claiming address: test.fifs.registrar.test.evan
buildKeyConfig
[error] could not decrypt; error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
? Claim which subdomain? test.fifs.registrar.test.evan.fifs.registrar.test.evan
? Should a business center be created at the given address? (default no) (y/N) Error: Connection error: Connection is not open on send()
    at C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\web3-providers\dist\web3-providers.cjs.js:497:27
    at new Promise (<anonymous>)
    at WebsocketProvider.sendPayload (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\web3-providers\dist\web3-providers.cjs.js:491:14)
    at WebsocketProvider._callee$ (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\web3-providers\dist\web3-providers.cjs.js:188:29)
    at tryCatch (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
Error: Connection error: Connection is not open on send()
    at C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\web3-providers\dist\web3-providers.cjs.js:497:27
    at new Promise (<anonymous>)
    at WebsocketProvider.sendPayload (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\web3-providers\dist\web3-providers.cjs.js:491:14)
    at WebsocketProvider._callee$ (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\web3-providers\dist\web3-providers.cjs.js:188:29)
    at tryCatch (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\BruzjaF\AppData\Roaming\npm\node_modules\generator-evan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7

I have double checked my .evan.json and it is in the proper path and keys are correct as well as the remaining contents of the file, since at first i thought it could be from mismatching keys.

Additional information, running on:

- Machine: Windows 10 Pro x64
- Node version: v10.15.3
- evan.prompt version: 0.14.0
- generator-evan version: 1.12.1
- yo version: 3.1.0

**Comment by S3bb1** [comment]
fixed by generator Version 1.12.2, please update

https://github.com/evannetwork/generator-evan/releases/tag/v1.12.2
